### ISSUE TITLE
ISR not in IRAM

### ISSUE THREAD

**Issue by simontims** [tstoegi/N96FY#1]
This is an amazingly useful library, thanks! I can't get it to work on a D1 Mini Pro, which is based on the ESP8266 but has extra RAM and an external antenna - otherwise, it should be the same.

When running, I get 'ISR not in RAM' followed by a reset (after this dump):

```
>>>stack>>>

ctx: cont
sp: 3ffffda0 end: 3fffffc0 offset: 01b0
3fffff50:  3ffe8596 3ffee2e1 3ffee344 4020277c  
3fffff60:  ad01a8c0 00ffffff 0101a8c0 3ffee3ac  
3fffff70:  3fffdad0 3ffee2e0 00000001 40100556  
3fffff80:  40204d88 ad01a8c0 00000000 40202414  
3fffff90:  3fffdad0 00000000 3ffee37c 40201118  
3fffffa0:  feefeffe feefeffe feefeffe 40202dac  
3fffffb0:  feefeffe feefeffe 3ffe8514 40100841  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
vac02aff5
~ld
```

Any tips very welcome!

**Comment by simontims** [comment]
Worked it out. In N96FY.cpp replaced:

```void N96FY::ISR_sensor()```

with

```void ICACHE_RAM_ATTR N96FY::ISR_sensor()```

**Comment by tstoegi** [comment]
Great! Thanks. Will asap commit.
